// <auto-generated />
using BMIApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMIApp.Migrations
{
    [DbContext(typeof(BmiContext))]
    [Migration("20230419121449_bmi")]
    partial class bmi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BMIApp.BMI.BMI", b =>
                {
                    b.Property<int>("IDBmi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBmi"));

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idpersons")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<double>("bmi")
                        .HasColumnType("float");

                    b.Property<double>("height")
                        .HasColumnType("float");

                    b.HasKey("IDBmi");

                    b.HasIndex("Idpersons");

                    b.ToTable("BMI", (string)null);
                });

            modelBuilder.Entity("BMIApp.BMI.Person", b =>
                {
                    b.Property<int>("IDperson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDperson"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CodeMeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDperson");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("BMIApp.BMI.BMI", b =>
                {
                    b.HasOne("BMIApp.BMI.Person", "Person")
                        .WithMany("bmi")
                        .HasForeignKey("Idpersons")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BMIApp.BMI.Person", b =>
                {
                    b.Navigation("bmi");
                });
#pragma warning restore 612, 618
        }
    }
}
